services:
  server:
    build: .
    develop:
      watch:
        - action: sync
          path: ./controllers
          target: /3dprint-api/controllers
          ignore:
            - node_modules
        - path: ./package.json
          action: rebuild
    environment:
      NODE_ENV: development
      DEV_DB_URL: mongodb://user:pass@database:27017/miapp?authSource=admin
      DEV_CORS_ALLOWED_ORIGINS: http://localhost:5173
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
